#!/usr/bin/env bash

if [ -z "$PYTHONPATH" ]; then
export PYTHONPATH=~/biology/devel/shared/pyutils
else
export PYTHONPATH=$PYTHONPATH:~/biology/devel/shared/pyutils
fi

echo $PYTHONPATH

./StreetViewCollect.py 37.276472 37.32647 -121.843538 -121.893538 10 files

